#
# Makefile for RISCV-specific library files.
#
lib-y += memmove.o memset.o memcpy.o thunk.o delay.o bitops.o extable.o usercopy.o 
#getuser.o putuser.o
#copy_user.o
#copy_from_user.o copy_to_user.o
lib-y += uaccess.o
lib-y += early_printk.o
